# Generated by Django 4.2.4 on 2023-08-06 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(null=True)),
                ('company', models.CharField(max_length=100, null=True)),
                ('platforms', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GoteraProductTable',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255, null=True)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('product_image_url', models.CharField(max_length=255, null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('product_description', models.CharField(max_length=1000, null=True)),
                ('data_sheet', models.CharField(max_length=1000, null=True)),
                ('more_info', models.CharField(max_length=1000, null=True)),
                ('category', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GoteraSubscriberTable',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=30, null=True)),
                ('phonenumber', models.CharField(max_length=15, null=True)),
                ('preferedpayment', models.CharField(max_length=40, null=True)),
                ('username', models.CharField(max_length=20, null=True)),
                ('password', models.CharField(max_length=30, null=True)),
                ('profilepicture', models.BinaryField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductTable',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100, null=True)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('product_image_url', models.CharField(max_length=200, null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('product_description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, null=True)),
                ('email', models.CharField(max_length=30, null=True)),
                ('password', models.CharField(max_length=50, null=True)),
                ('profile_picture', models.BinaryField(null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('country', models.CharField(max_length=50, null=True)),
                ('username', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BillingInformation',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='gotera.usertable')),
                ('country', models.CharField(max_length=255, null=True)),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('company_name', models.CharField(max_length=255, null=True)),
                ('street_address', models.CharField(max_length=255, null=True)),
                ('apartment', models.CharField(max_length=255, null=True)),
                ('town', models.CharField(max_length=255, null=True)),
                ('state', models.CharField(max_length=255, null=True)),
                ('postcode', models.CharField(max_length=255, null=True)),
                ('email_address', models.CharField(max_length=255, null=True)),
                ('phone_number', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserCartedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carted_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gotera.producttable')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gotera.usertable')),
            ],
        ),
        migrations.CreateModel(
            name='UserBoughtProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_quantity', models.IntegerField()),
                ('bought_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gotera.producttable')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gotera.usertable')),
            ],
        ),
        migrations.CreateModel(
            name='GoteraUserCartedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carted_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gotera.producttable')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gotera.usertable')),
            ],
        ),
        migrations.CreateModel(
            name='GoteraUserBoughtProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_quantity', models.IntegerField()),
                ('bought_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gotera.producttable')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gotera.usertable')),
            ],
        ),
        migrations.CreateModel(
            name='GoteraCheckoutProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(null=True)),
                ('product_name', models.CharField(max_length=255, null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(max_length=50, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gotera.usertable')),
            ],
        ),
        migrations.CreateModel(
            name='CheckoutProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(null=True)),
                ('product_name', models.CharField(max_length=255, null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(max_length=50, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gotera.usertable')),
            ],
        ),
    ]
